# Application Configuration
spring.application.name=resourcemanager-ms
server.port=8082

# Virtual Threads Configuration
spring.threads.virtual.enabled=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging Configuration
logging.level.open.ipaas.resourcemanager=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud=INFO