spring.application.name=resourceaccesscontrol-ms
server.port=8083
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
spring.threads.virtual.enabled=true

# SpringDoc OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
logging.level.open.ipaas.resourceaccesscontrol=DEBUG
